# مدل‌های embedding برای مقایسه
models:
  - "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  - "sentence-transformers/distiluse-base-multilingual-cased-v2"
  - "intfloat/multilingual-e5-base"

# تنظیمات chunking
chunking:
  word_chunk_size: 150
  word_overlap: 25
  sentences_per_chunk: 5

# تنظیمات بازیابی
retrieval:
  methods: ["bm25", "dense", "tfidf"]
  top_k: [1, 3, 5, 10]

# تنظیمات ارزیابی
evaluation:
  test_size: 0.2
  batch_size: 32